security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\UserAccount:
      algorithm: 'sha256'

  providers:
    # Utilisé pour recharger l'utilisateur à partir de la session et d'autres fonctionnalités (par exemple, switch_user)
    db_provider:
      entity:
        class: App\Entity\UserAccount # Remplacement de AppBundle par App
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Commenté temporairement pour éviter les erreurs
    # main:
    #     lazy: true
    #     provider: app_user_provider

    # Activation de différentes méthodes d'authentification
    # https://symfony.com/doc/current/security.html#the-firewall

    # https://symfony.com/doc/current/security/impersonating_user.html
    # switch_user: true

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  # Facilité de contrôle d'accès pour de grandes sections de votre site
  # Remarque : Seule la première règle d'accès qui correspond sera utilisée

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/doc, roles: PUBLIC_ACCESS}
    - { path: ^/api/tweets, roles: PUBLIC_ACCESS} #Permettre l'accès au requête GET en public
    - { path: ^/api/responses, roles: PUBLIC_ACCESS} #Permettre l'accès au requête GET en public
    - { path: ^/api/user, roles: PUBLIC_ACCESS,  methods: [POST]} #Pouvoir se créer un utilisateur admin rapidement
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

# Configuration spécifique pour les tests
# Il est important de noter que ces paramètres réduisent la sécurité pour accélérer les tests
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: "sha256"
        cost: 4 # Valeur la plus basse possible pour bcrypt
        time_cost: 3 # Valeur la plus basse possible pour argon
        memory_cost: 10 # Valeur la plus basse possible pour argon
